apiVersion: v1
kind: Service
metadata:
  name: {{ include "workflow-definition-service.fullname" . }}
  labels:
    {{- include "workflow-definition-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "workflow-definition-service.selectorLabels" . | nindent 4 }}
